shuffle: roundrobin
# Deployment mode: 'local' for local deployment, 'ansible' for remote deployment via Ansible
deployment_mode: ansible
config:
  activeEpoch: 18
  keyType: "hash-sig"
validators:
  - name: "ream_0"
    # node id bc531fc1a99a896acb45603f28a32f81ae607480af46435009de4609370cb7bb
    # peer id 16Uiu2HAmPQhkD6Zg5Co2ee8ShshkiY4tDePKFARPpCS2oKSLj1E1
    privkey: "af27950128b49cda7e7bc9fcb7b0270f7a3945aa7543326f3bfdbd57d2a97a32"
    enrFields:
      #verify /ip4/127.0.0.1/udp/9001/quic-v1/p2p/16Uiu2HAmPQhkD6Zg5Co2ee8ShshkiY4tDePKFARPpCS2oKSLj1E1
      ip: "77.42.27.219"
      quic: 9001
    metricsPort: 9095
    isAggregator: true
    devnet: 1
    count: 1
  - name: "qlean_0"
    # TODO: add a third entry in nodes.yaml corresponding to this
    privkey: "c2bbdac5e876b3e9d4b8b6b8c2bbdac5e876b3e9d4b8b6b8c2bbdac5e876b3e9"
    enrFields:
      #verify /ip4/127.0.0.1/udp/9001/quic-v1/p2p/16Uiu2HAmPQhkD6Zg5Co2ee8ShshkiY4tDePKFARPpCS2oKSLj1E1
      ip: "46.224.123.220"
      quic: 9001
    metricsPort: 9095
    isAggregator: false
    count: 1
  - name: "lantern_0"
    # node id a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2
    # peer id 16Uiu2HAm7TYVs6qvDKnrovd9m4vvRikc4HPXm1WyLumKSe5fHxBv
    privkey: "d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5"
    # verify /ip4/127.0.0.1/udp/9004/quic-v1/p2p/16Uiu2HAm7TYVs6qvDKnrovd9m4vvRikc4HPXm1WyLumKSe5fHxBv
    enrFields:
      ip: "46.224.135.177"
      quic: 9001
    metricsPort: 9095
    isAggregator: false
    count: 1
  - name: "ethlambda_0"
    privkey: "299550529a79bc2dce003747c52fb0639465c893e00b0440ac66144d625e066a"
    enrFields:
      ip: "78.47.44.215"
      quic: 9001
    metricsPort: 9095
    isAggregator: false
    count: 1
